name: imp_approval
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  lucide_icons: ^0.257.0
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  camera: ^0.10.5+3
  google_ml_kit: ^0.16.2
  image: ^3.3.0
  path_provider: ^2.1.0
  tflite_flutter: ^0.9.0
  tflite_flutter_helper_plus: ^0.0.2
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  image_picker: ^1.0.2
  google_ml_face_detection: ^0.0.3
  shimmer: ^3.0.0
  google_maps_flutter: ^2.4.0
  getwidget: ^4.0.0
  sizer: ^2.0.15
  # download file and save
  dio: ^5.3.2
  flutter_pdfview: ^1.3.1
  flutter_svg: ^2.0.7
  permission_handler: ^11.0.0
  connectivity_plus: ^4.0.2
  network_info_plus: ^4.0.2
  ntp: ^2.0.0
  path: ^1.8.3
  open_file: ^3.3.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  flutter_typeahead: ^4.8.0
  onesignal_flutter: ^5.0.3
  cached_network_image: ^3.3.0
  get: ^4.6.5
  objectbox: ^2.3.1
  objectbox_flutter_libs: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: ^2.3.1

flutter:
  uses-material-design: true
  assets :
  - assets/
  - assets/mobilefacenet.tflite
  - assets/img/
  - assets/gif/